"""Single-source constants for 99k signup/payment states."""

SIGNUP_STATUS_RESERVED = "reserved"
SIGNUP_STATUS_PAID = "paid"
SIGNUP_STATUS_CANCELLED = "cancelled"
SIGNUP_STATUS_EXPIRED = "expired"
SIGNUP_STATUS_COMPLETED = "completed"
SIGNUP_STATUS_NOT_COMPLETED = "not_completed"

SIGNUP_ACTIVE_STATUSES = {
    SIGNUP_STATUS_PAID,
    SIGNUP_STATUS_COMPLETED,
    SIGNUP_STATUS_NOT_COMPLETED,
}

SIGNUP_TRANSIENT_STATUSES = {
    SIGNUP_STATUS_RESERVED,
    SIGNUP_STATUS_CANCELLED,
    SIGNUP_STATUS_EXPIRED,
}

SIGNUP_ALLOWED_STATUSES = SIGNUP_ACTIVE_STATUSES | SIGNUP_TRANSIENT_STATUSES

PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_VERIFIED = "verified"
PAYMENT_ALLOWED_STATUSES = {PAYMENT_STATUS_PENDING, PAYMENT_STATUS_VERIFIED}
