ALTER TABLE jump_99k_settings
    ADD COLUMN IF NOT EXISTS insurance_role_id BIGINT,
    ADD COLUMN IF NOT EXISTS insurance_channel_id BIGINT,
    ADD COLUMN IF NOT EXISTS default_max_slots INT NOT NULL DEFAULT 5;

ALTER TABLE jump_99k_sessions
    ADD COLUMN IF NOT EXISTS price_item TEXT,
    ADD COLUMN IF NOT EXISTS price_quantity INT;

ALTER TABLE jump_99k_signups
    ADD COLUMN IF NOT EXISTS payment_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS payment_verified_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS overdose_flag BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS overdose_detected_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS overdose_meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS insurance_offer_sent_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS jump_99k_insurers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    insurer_discord_id BIGINT NOT NULL,
    display_name TEXT NOT NULL,
    policy_summary TEXT NOT NULL,
    contact_instructions TEXT NOT NULL,
    insurer_meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_by_discord_id BIGINT,
    verified_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (guild_id, insurer_discord_id)
);

CREATE TABLE IF NOT EXISTS jump_99k_insurance_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES jump_99k_sessions(id) ON DELETE CASCADE,
    participant_discord_id BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('requested','claimed','denied','accepted','declined','completed')),
    requested_at TIMESTAMPTZ,
    claimed_by_discord_id BIGINT,
    claimed_at TIMESTAMPTZ,
    denied_by_discord_id BIGINT,
    denied_at TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    declined_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    channel_id BIGINT,
    message_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (session_id, participant_discord_id)
);

CREATE INDEX IF NOT EXISTS idx_jump_99k_insurance_requests_session ON jump_99k_insurance_requests(session_id);
ALTER TABLE guild_settings ADD COLUMN IF NOT EXISTS default_max_slots INT NOT NULL DEFAULT 5;
