BEGIN;

ALTER TABLE IF EXISTS public.payment_receipts
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS verified_by_discord_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS receipt_meta JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMIT;
