BEGIN;
ALTER TABLE IF EXISTS jump_99k_signups ADD COLUMN IF NOT EXISTS participant_torn_name TEXT;
ALTER TABLE IF EXISTS jump_99k_insurance_requests ADD COLUMN IF NOT EXISTS requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
COMMIT;
