DROP TABLE IF EXISTS happy_jump_readiness;
DROP TABLE IF EXISTS happy_jump_waitlist;
DROP TABLE IF EXISTS happy_jump_signups;
DROP TABLE IF EXISTS happy_jump_sessions;
DROP TABLE IF EXISTS jump_99k_session_totals;

DROP TABLE IF EXISTS payment_receipts;
CREATE TABLE payment_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_type TEXT NOT NULL,
    feature_ref_id TEXT NOT NULL,
    payer_discord_id BIGINT NOT NULL,
    payer_torn_user_id INT NULL,
    amount INT NOT NULL,
    currency TEXT NOT NULL,
    receipt_hash TEXT NOT NULL,
    receipt_meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL CHECK (status IN ('pending','verified','rejected')),
    verified_by_discord_id BIGINT NULL,
    verified_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(feature_type, feature_ref_id, payer_discord_id, receipt_hash)
);
CREATE INDEX idx_payment_receipts_feature_ref ON payment_receipts (feature_type, feature_ref_id);
CREATE INDEX idx_payment_receipts_payer ON payment_receipts (payer_discord_id);
CREATE INDEX idx_payment_receipts_status ON payment_receipts (status);

CREATE TABLE IF NOT EXISTS jump_99k_settings (
    guild_id BIGINT PRIMARY KEY,
    host_role_id BIGINT NOT NULL,
    announce_channel_id BIGINT NULL,
    payee_discord_id BIGINT NULL,
    currency_default TEXT NOT NULL DEFAULT 'cash',
    default_max_slots INT NOT NULL DEFAULT 5,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jump_99k_totals (
    guild_id BIGINT PRIMARY KEY,
    completed_count INT NOT NULL DEFAULT 0,
    not_completed_count INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jump_99k_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    host_discord_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    scheduled_start_text TEXT NULL,
    max_slots INT NOT NULL,
    notes TEXT NULL,
    status TEXT NOT NULL CHECK (status IN ('open','closed')),
    announce_message_id BIGINT NULL,
    announce_channel_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS jump_99k_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES jump_99k_sessions(id) ON DELETE CASCADE,
    guild_id BIGINT NOT NULL,
    discord_id BIGINT NOT NULL,
    torn_user_id INT NULL,
    status TEXT NOT NULL CHECK (status IN ('signed_up','cancelled','completed','not_completed')),
    signed_up_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(session_id, discord_id)
);

CREATE TABLE IF NOT EXISTS jump_99k_readiness (
    session_id BIGINT NOT NULL REFERENCES jump_99k_sessions(id) ON DELETE CASCADE,
    discord_id BIGINT NOT NULL,
    energy INT NULL,
    energy_max INT NULL,
    drug_cooldown INT NULL,
    status_text TEXT NULL,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(session_id, discord_id)
);
